apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  labels:
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webclient
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webclient
  template:
    metadata:
      labels:
        app: webclient
        tier: frontend
    spec:
      containers:
        - name: curl
          image: curlimages/curl:8.9.1
          command: ["sleep", "infinity"]
