apiVersion: v1
kind: Service
metadata:
  name: web-app
spec:
  type: LoadBalancer
  selector:
    app: web-app
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-app-config
data:
  api_token: "AKIA1234567890ABCDEF"
  admin_user: "root"
  debug: "true"
