apiVersion: cilium.io/v1alpha1
kind: TracingPolicyNamespaced
metadata:
  name: trace-process-credentials
  namespace: evaluation
spec:
  kprobes:
    - call: __sys_setuid
      syscall: true
      args:
        - index: 0
          type: int
      selectors:
        - matchPIDs:
            - operator: NotIn
              followForks: true
              isNamespacePID: true
              values: [0, 1]
    - call: __sys_setgid
      syscall: true
      args:
        - index: 0
          type: int
    - call: cap_capable
      syscall: false
      args:
        - index: 2
          type: int
        - index: 3
          type: int
